# Base on offical Node.js Alpine image
FROM node:alpine

# Set working directory
WORKDIR /app

#args
ARG ARANGO_URL
ARG ARANGO_USERNAME
ARG ARANGO_PASSWORD
ARG ARANGO_DATABASE_NAME
ARG ARANGO_MAX_SOCKETS

ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_SECURE
ARG EMAIL_TO
ARG EMAIL_USERNAME
ARG EMAIL_PASSWORD

ARG S3_ENDPOINT
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY

ARG SESSION_COOKIE_NAME
ARG SESSION_SECRET

ARG NEXT_PUBLIC_WEBSITE_DOMAIN
ARG NEXT_PUBLIC_STATIC_DOMAIN

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production
ENV PORT 3000

COPY . ./

# Build app
RUN npm run build

EXPOSE 3000

# Run npm start script when container starts
CMD [ "npm", "run", "start" ]